name: Build
on:
  workflow_dispatch:  
    inputs:  
      logLevel:  
        description: 'Log level'  
        required: true  
        default: 'warning'
  push:  
    branches: [ "dev" ]  
  pull_request:  
    branches: [ "dev" ] 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ 'admin', 'core', 'bedtime', 'enchantments', 'permissions', 'portals', 'regions', 'trifles', 'velocity' ]

    steps:
      - uses: actions/checkout@v3.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Gradle build
        run: |
          cd vane-${{ matrix.project }}
          gradle build
          # Get the Git hash
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV

      - name: Upload JAR
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v3
        with:
          name: vane-${{ matrix.project }}-${{ env.git_hash }}.jar
          path: target/vane-${{ matrix.project }}-*.jar
